"""
run_randommode.py
=================
Multi-grain polycrystal solidification with Voronoi random grain structure.

Purpose
-------
Simulate competitive growth of multiple solid grains growing into an
undercooled melt.  Grain shapes are generated by Voronoi tessellation:
n_solid seed points are placed at random in the x-y plane and each grid
cell is assigned to the nearest seed.  The solid-liquid interface is
initialised as a flat tanh profile at y = seed_height.

What this mode checks
---------------------
  * Many-grain phase field evolution (number_of_grain > 3).
  * Multiple grain boundary types evolving simultaneously.
  * Orientation-dependent competitive growth across many grains.
  * MAX_GRAINS budget check for practical simulation sizes.

Phases
------
  gid = 0        : liquid   (always; dummy quaternion [0, 0, 0, 1])
  gid = 1..N-1   : solid grains  (N = n_solid + 1 = number_of_grain)

Output
------
  result/randommode/step_0.png
  result/randommode/initial_phase_map.png
  result/randommode/initial_temperature.png
  result/randommode/step_{N}.png  (every save_every steps)

Config block (config.yaml -> randommode)
----------------------------------------
  randommode:
    seed_height: 32
    n_solid: 10
    random_seed: 42
    orientation_mode: "random"   # "random" or "file"
    orientation_seed: 42
    orientation_csv: ""          # path to CSV when orientation_mode = "file"
"""

import os
import math
import numpy as np
import yaml
from numba import cuda

from gpu_kernels import (
    kernel_update_nfmf,
    kernel_update_phasefield_active,
    kernel_update_temp,
)
from orientation_utils import (
    assign_quaternions_to_grains,
    compute_rotated_n111,
)
from seed_modes import (
    generate_random_grain_map,
    init_phi_from_grain_map,
    init_temperature_field,
    build_interaction_matrices,
)
from plot_utils import save_phase_map, save_temperature_map


# --- Configuration -----------------------------------------------------------

CONFIG_PATH = "config.yaml"
with open(CONFIG_PATH, "r") as f:
    cfg = yaml.safe_load(f)

pi = math.pi

# Grid
nx     = cfg["grid"]["nx"]
ny     = cfg["grid"]["ny"]
dx     = cfg["grid"]["dx"]
dy     = cfg["grid"]["dy"]
dt     = cfg["grid"]["dt"]
nsteps = cfg["grid"]["nsteps"]

# Physical
T_melt    = cfg["physical"]["T_melt"]
G         = cfg["physical"]["G"]
V_pulling = cfg["physical"]["V_pulling"]
Sf        = cfg["physical"]["Sf"]

# Interface
delta     = cfg["interface"]["delta_factor"] * dx
gamma_100 = cfg["interface"]["gamma_100"]
gamma_GB  = cfg["interface"]["gamma_GB"]

# Anisotropy
a0      = cfg["anisotropy"]["a0_deg"] * pi / 180.0
delta_a = cfg["anisotropy"]["delta_a"]
mu_a    = cfg["anisotropy"]["mu_a"]
p_round = cfg["anisotropy"]["p_round"]
ksi     = cfg["anisotropy"]["ksi"]
omg     = 1.0 / (cfg["anisotropy"]["omg_deg"] * pi / 180.0)

# Mobility
M_SL = cfg["mobility"]["M_SL"]
M_GB = M_SL * cfg["mobility"]["M_GB_ratio"]

# GPU
MAX_GRAINS      = cfg["gpu"]["MAX_GRAINS"]
threadsperblock = tuple(cfg["gpu"]["threads_per_block"])

# Output
save_every = cfg["output"]["save_every"]

# randommode-specific settings
rm_cfg           = cfg.get("randommode", {})
seed_height      = int(rm_cfg.get("seed_height", cfg["seed"].get("height", 32)))
n_solid          = int(rm_cfg.get("n_solid", 5))
random_seed      = int(rm_cfg.get("random_seed", 42))
orientation_mode = str(rm_cfg.get("orientation_mode", "random"))
orientation_seed = int(rm_cfg.get("orientation_seed", 42))
orientation_csv  = rm_cfg.get("orientation_csv", None) or None
out_dir          = "result/randommode"
os.makedirs(out_dir, exist_ok=True)

number_of_grain = n_solid + 1  # liquid (gid=0) + n_solid solids
N = number_of_grain

if number_of_grain > MAX_GRAINS:
    raise RuntimeError(
        f"number_of_grain={number_of_grain} exceeds MAX_GRAINS={MAX_GRAINS}. "
        f"Reduce randommode.n_solid or increase gpu.MAX_GRAINS in config.yaml.")


# --- Interface parameter helpers ---------------------------------------------

def eps_from_gamma(gamma):
    """eps = sqrt(8 * delta * gamma / pi^2)."""
    return math.sqrt(8.0 * delta * gamma / (pi * pi))


def w_from_gamma(gamma):
    """w = 4 * gamma / delta."""
    return 4.0 * gamma / delta


def mij_from_M(M):
    """m_ij = (pi^2 / (8 * delta)) * M."""
    return (pi * pi / (8.0 * delta)) * M


eps0_sl  = eps_from_gamma(gamma_100)
w0_sl    = w_from_gamma(gamma_100)
m_sl_phi = mij_from_M(M_SL)
eps_GB   = eps_from_gamma(gamma_GB)
w_GB     = w_from_gamma(gamma_GB)
m_GB_phi = mij_from_M(M_GB)


# --- Grain orientations ------------------------------------------------------

grain_quaternions = assign_quaternions_to_grains(
    n_solid,
    mode=orientation_mode,
    orientation_seed=orientation_seed,
    csv_path=orientation_csv,
)

grain_n111 = compute_rotated_n111(grain_quaternions)


# --- Interaction matrices ----------------------------------------------------

wij, aij, mij = build_interaction_matrices(
    N, eps0_sl, w0_sl, m_sl_phi, eps_GB, w_GB, m_GB_phi)


# --- APT arrays --------------------------------------------------------------

mf_cpu = np.zeros((MAX_GRAINS, nx, ny), dtype=np.int32)
nf_cpu = np.zeros((nx, ny), dtype=np.int32)


# --- Initial conditions ------------------------------------------------------

grain_map = generate_random_grain_map(nx, ny, n_solid, random_seed=random_seed)
phi_cpu   = init_phi_from_grain_map(
    grain_map, n_solid, nx, ny, dy, delta, seed_height)
temp_cpu  = init_temperature_field(nx, ny, T_melt, G, dy, seed_height)


# --- Startup log -------------------------------------------------------------

print("Mode             : randommode")
print(f"Grid             : {nx}x{ny}, dx={dx:.1e}, dt={dt:.1e}, nsteps={nsteps}")
print(f"Seed height      : {seed_height}")
print(f"n_solid          : {n_solid}  (number_of_grain={number_of_grain})")
print(f"Orientation mode : {orientation_mode}  (seed={orientation_seed})")
print("Grain quaternions (gid=0 liquid, 1..N-1 solid):")
for gid, q in enumerate(grain_quaternions):
    tag = "liquid" if gid == 0 else f"grain{gid}"
    print(f"  gid={gid} [{tag}]  q={np.round(q, 4)}")
print(f"Output dir       : {out_dir}")


# --- Save initial state ------------------------------------------------------

save_phase_map(phi_cpu, out_dir, "step_0.png",
               number_of_grain, title="randommode -- step 0")
save_phase_map(phi_cpu, out_dir, "initial_phase_map.png",
               number_of_grain, title="randommode -- Initial Phase Map")
save_temperature_map(temp_cpu, out_dir, "initial_temperature.png",
                     title="Initial Temperature [K]")
print("Saved step_0.png, initial_phase_map.png, initial_temperature.png")


# --- GPU transfer ------------------------------------------------------------

phi_cpu  = phi_cpu.astype(np.float32)
temp_cpu = temp_cpu.astype(np.float32)

d_phi     = cuda.to_device(phi_cpu)
d_phi_new = cuda.to_device(phi_cpu.copy())
d_temp    = cuda.to_device(temp_cpu)
d_mf      = cuda.to_device(mf_cpu)
d_nf      = cuda.to_device(nf_cpu)
d_wij     = cuda.to_device(wij.astype(np.float32))
d_aij     = cuda.to_device(aij.astype(np.float32))
d_mij     = cuda.to_device(mij.astype(np.float32))
d_n111    = cuda.to_device(grain_n111.astype(np.float32))

blockspergrid = (math.ceil(nx / threadsperblock[0]),
                 math.ceil(ny / threadsperblock[1]))

cooling_rate = np.float32(G * V_pulling * dt)
T_melt_f     = np.float32(T_melt)
Sf_f         = np.float32(Sf)
g2_floor_f   = np.float32((0.1 / dx) ** 2)


# --- Main time evolution loop ------------------------------------------------

print(f"\nStarting time evolution ({nsteps} steps, saving every {save_every}) ...")

for nstep in range(1, nsteps + 1):

    kernel_update_temp[blockspergrid, threadsperblock](
        d_temp, cooling_rate, nx, ny)

    kernel_update_nfmf[blockspergrid, threadsperblock](
        d_phi, d_mf, d_nf, nx, ny, number_of_grain)

    kernel_update_phasefield_active[blockspergrid, threadsperblock](
        d_phi, d_phi_new, d_temp, d_mf, d_nf,
        d_wij, d_aij, d_mij, d_n111,
        nx, ny, number_of_grain,
        np.float32(dx), np.float32(dt),
        T_melt_f, Sf_f,
        np.float32(eps0_sl), np.float32(w0_sl),
        np.float32(a0), np.float32(delta_a), np.float32(mu_a), np.float32(p_round),
        g2_floor_f, np.float32(ksi), np.float32(omg),
    )

    d_phi, d_phi_new = d_phi_new, d_phi

    if nstep % save_every == 0:
        current_phi = d_phi.copy_to_host()
        save_phase_map(current_phi, out_dir, f"step_{nstep}.png",
                       number_of_grain, title=f"randommode -- step {nstep}")
        print(f"  saved step_{nstep}.png")

print("\nDone.")
